<a href="https://colab.research.google.com/github/SharviE29/Machine_learning_models/blob/main/cbow_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.seed(10)
z1=10*np.random.rand(5,1)-5
print(z1)

[[ 2.71320643]
 [-4.79248051]
 [ 1.33648235]
 [ 2.48803883]
 [-0.01492988]]


In [3]:
h=z1.copy()

In [4]:
h<0
#to determine only negative values

array([[False],
       [ True],
       [False],
       [False],
       [ True]])

In [5]:
h[h<0]=0
print(h)

[[2.71320643]
 [0.        ]
 [1.33648235]
 [2.48803883]
 [0.        ]]


In [6]:
z=np.array([3,7,12.5,4,5])
ez=np.exp(z)
print(ez)


[2.00855369e+01 1.09663316e+03 2.68337287e+05 5.45981500e+01
 1.48413159e+02]


In [7]:
sum_ez=np.sum(ez)
print(sum_ez)

269657.0165253618


In [10]:
def softmax(z):
  ez=np.exp(z)
  sum_ez=np.sum(ez)
  return ez/sum_ez

In [11]:
softmax(z)

array([7.44854971e-05, 4.06677035e-03, 9.95105894e-01, 2.02472573e-04,
       5.50377517e-04])