<a href="https://colab.research.google.com/github/SharviE29/Machine_learning_models/blob/main/sample1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset=pd.read_csv("sharvu.csv")
print(dataset.head)

<bound method NDFrame.head of                     Food Measure  Grams  Calories  Proein    Fa  Sa.Fa  Fiber  \
0             Cows' milk    1 q.  976.0     660.0    32.0  40.0   36.0    0.0   
1              Milk skim    1 q.  984.0     360.0    36.0   NaN    NaN    0.0   
2               Buermilk   1 cup  246.0     127.0     9.0   5.0    4.0    0.0   
3    Evaporaed, undilued   1 cup  252.0     345.0    16.0  20.0   18.0    0.0   
4         Fortified milk  1 cups  237.0     229.0    14.0   7.0    3.0    0.0   
..                   ...     ...    ...       ...     ...   ...    ...    ...   
333   Frui-flavored soda  12 oz.  346.0     161.0     0.0   0.0    0.0    0.0   
334           Ginger ale  12 oz.  346.0     105.0     0.0   0.0    0.0    0.0   
335             Roo beer  12 oz.  346.0     140.0     0.0   0.0    0.0    0.0   
336               Coffee   1 cup  230.0       3.0     NaN   0.0    0.0    0.0   
337                   ea   1 cup  230.0       4.0     0.0   NaN    0.0    0.0  

In [ ]:
X= dataset.iloc[:,2:9].values
y =dataset.iloc[:,-1].values


In [ ]:
print(X)

[[976. 660.  32. ...  36.   0.  48.]
 [984. 360.  36. ...  nan   0.  52.]
 [246. 127.   9. ...   4.   0.  13.]
 ...
 [346. 140.   0. ...   0.   0.  35.]
 [230.   3.  nan ...   0.   0.   1.]
 [230.   4.   0. ...   0.   0.   1.]]


In [ ]:
print(y)

[1 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 1 1 0 1 1 1 0 0 1 0 1 1 0 0 0 1 1 1 0 0
 1 0 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0
 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 0 1 1 0 0 0
 1 0 0 1 0 1 1 0 1 0 1 1 0 1 1 1 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 0 1 0 1
 1 0 0 1 0 1 1 0 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0
 1 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 1 1 0 0 0 1
 0 1 1 0 1 0 1 0 1 0 0 0 1 1 1 1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1
 1 1 1 0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 1 1 0 1 1 0 1 0 0 0 0
 0 0 1 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values= np.nan, strategy='mean')

imp = imp.fit(X)
imp = imp.transform(X)

In [ ]:
print(imp)

[[976.         660.          32.         ...  36.           0.
   48.        ]
 [984.         360.          36.         ...   6.74613003   0.
   52.        ]
 [246.         127.           9.         ...   4.           0.
   13.        ]
 ...
 [346.         140.           0.         ...   0.           0.
   35.        ]
 [230.           3.           9.61409396 ...   0.           0.
    1.        ]
 [230.           4.           0.         ...   0.           0.
    1.        ]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(imp,y,test_size=0.1,random_state=0)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred=classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 9  6]
 [ 9 10]]


0.5588235294117647